<template>
  <div class="page-shell seckill-page">
    <header class="page-heading"><div><span class="section-index">限时库存</span><h1>限时抢票</h1></div><p>所有库存由系统实时确认，提交成功后可凭请求编号查询订单。</p></header>
    <div v-if="loading" class="session-list"><div v-for="n in 4" :key="n" class="session-skeleton skeleton"/></div>
    <div v-else-if="error" class="state-block"><div><h2>场次加载失败</h2><p>{{ error }}</p><button class="ui-button" type="button" @click="loadSessions">重新加载</button></div></div>
    <template v-else>
      <section class="session-section"><header><span>LIVE</span><h2>正在抢票</h2><strong>{{ activeSessions.length }}</strong></header><div v-if="!activeSessions.length" class="empty-row">当前没有进行中的场次</div><div class="session-list"><article v-for="session in activeSessions" :key="session.id" class="session-row"><div class="session-state active">进行中</div><div class="session-main"><span>{{ formatTime(session.endTime) }} 结束</span><h3>{{ session.show?.name || '演出场次' }}</h3><p>{{ session.show?.venue || '场馆信息待确认' }}</p></div><div class="session-stock"><span>实时余票</span><strong>{{ session.stock ?? 0 }}</strong></div><div class="session-price"><span>抢票价</span><strong>¥{{ session.seckillPrice }}</strong></div><button class="ui-button ui-button--primary" type="button" :disabled="session.stock <= 0" @click="goToSeckillDetail(session.id)">{{ session.stock > 0 ? '进入抢票' : '已售罄' }}</button></article></div></section>
      <section class="session-section upcoming"><header><span>NEXT</span><h2>即将开始</h2><strong>{{ upcomingSessions.length }}</strong></header><div v-if="!upcomingSessions.length" class="empty-row">暂无即将开始的场次</div><div class="session-list"><article v-for="session in upcomingSessions" :key="session.id" class="session-row"><div class="session-state">待开始</div><div class="session-main"><span>{{ formatTime(session.startTime) }}</span><h3>{{ session.show?.name || '演出场次' }}</h3><p>{{ session.show?.venue || '场馆信息待确认' }}</p></div><div class="countdown"><span>距离开始</span><strong>{{ countdown(session.startTime) }}</strong></div><div class="session-price"><span>抢票价</span><strong>¥{{ session.seckillPrice }}</strong></div><button class="ui-button" type="button" @click="goToSeckillDetail(session.id)">查看场次</button></article></div></section>
    </template>
  </div>
</template>

<script setup>
import { onMounted,onUnmounted,ref } from 'vue';import { useRouter } from 'vue-router';import dayjs from 'dayjs';import { seckillApi } from '../../api/seckill';
const router=useRouter(),activeSessions=ref([]),upcomingSessions=ref([]),loading=ref(true),error=ref('');const tick=ref(0);let timer;
const loadSessions=async()=>{try{loading.value=true;error.value='';const [active,upcoming]=await Promise.all([seckillApi.getActiveSessions(),seckillApi.getUpcomingSessions()]);if(active.code!==200||upcoming.code!==200)throw new Error(active.message||upcoming.message);activeSessions.value=active.data||[];upcomingSessions.value=upcoming.data||[];}catch(err){error.value=err.message||'请稍后再试';}finally{loading.value=false;}};
const formatTime=(time)=>dayjs(time).format('MM月DD日 HH:mm');const countdown=(time)=>{tick.value;const seconds=Math.max(0,dayjs(time).diff(dayjs(),'second'));const h=String(Math.floor(seconds/3600)).padStart(2,'0'),m=String(Math.floor(seconds%3600/60)).padStart(2,'0'),s=String(seconds%60).padStart(2,'0');return `${h}:${m}:${s}`;};const goToSeckillDetail=(id)=>router.push(`/seckill/${id}`);
onMounted(()=>{loadSessions();timer=setInterval(()=>tick.value++,1000);});onUnmounted(()=>clearInterval(timer));
</script>

<style scoped>
.section-index,.session-section>header>span{display:block;color:var(--brand);font-size:12px;font-weight:800}.session-section{margin-top:44px}.session-section>header{display:grid;grid-template-columns:70px 1fr auto;align-items:end;padding-bottom:14px;border-bottom:1px solid var(--ink)}.session-section>header h2{font-size:23px}.session-section>header strong{font-size:18px}.session-row{min-height:132px;display:grid;grid-template-columns:72px minmax(220px,1fr) 110px 110px 110px;align-items:center;gap:22px;border-bottom:1px solid var(--line)}.session-state{color:var(--ink-3);font-weight:800}.session-state.active{color:var(--brand)}.session-main>span,.session-stock span,.session-price span,.countdown span{display:block;margin-bottom:5px;color:var(--ink-3);font-size:12px}.session-main h3{margin-bottom:6px;font-size:18px}.session-main p{color:var(--ink-2)}.session-stock strong,.session-price strong,.countdown strong{font-size:18px}.session-price strong{color:var(--brand)}.countdown strong{font-variant-numeric:tabular-nums}.empty-row{padding:38px 0;color:var(--ink-3);border-bottom:1px solid var(--line)}.session-skeleton{height:132px;margin-top:1px}.state-block p{margin:8px 0 18px;color:var(--ink-3)}
@media(max-width:850px){.session-row{grid-template-columns:56px 1fr 90px 100px}.session-stock,.countdown{display:none}}@media(max-width:600px){.session-section>header{grid-template-columns:52px 1fr auto}.session-row{grid-template-columns:1fr auto;gap:10px;padding:18px 0}.session-state{grid-column:1/-1;font-size:12px}.session-price{display:none}.session-row .ui-button{grid-column:2;grid-row:2/4}.session-main{grid-column:1}.page-heading p{max-width:34ch}}
</style>
